language: node_js

# Allow Travis tests to run in containers.
sudo: false

node_js:
  - "6"
  - "8"

cache:
  directories:
    - $HOME/.npm

before_install:
  - npm install -g yarn
  - yarn --version

install:
  - yarn bootstrap

script:
  - yarn test
