language: node_js

# Allow Travis tests to run in containers.
sudo: false

node_js:
  - "6"
  - "8"

cache:
  directories:
    - $HOME/.npm

before_install:
  - npm install -g npm@5

install:
  - npm install

script:
  - npm test
  - npm run test:smoke
